pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('travissscottt-dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {

        stage('Clone Repository') {
            steps {
                cleanWs()
                sh 'git clone -b master https://github.com/Dolmachi/MLOps-lab3.git'
            }
        }

        stage('Install Ansible') {
            steps {
                dir('MLOps-lab3') {
                    sh '''
                        sudo apt-get update
                        sudo apt-get install -y python3-pip
                        pip3 install ansible
                        ansible --version
                    '''
                }
            }
        }

        stage('Decrypt config_secret.ini') {
            steps {
                dir('MLOps-lab3') {
                    withCredentials([string(credentialsId: 'vault_key', variable: 'VAULT_KEY')]) {
                        sh '''
                            echo "$VAULT_KEY" > vault-key.txt
                            ansible-vault decrypt config_secret.ini --vault-password-file vault-key.txt
                            rm vault-key.txt
                        '''
                    }
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('MLOps-lab3') {
                    sh '''
                        bash -c "
                            python3 -m venv venv &&
                            . venv/bin/activate &&
                            pip install -r requirements.txt &&
                            pytest src/unit_tests --cov=src
                        "
                    '''
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Build Images and Run Containers') {
            steps {
                dir('MLOps-lab3') {
                    withCredentials([
                        string(credentialsId: 'mongo-username', variable: 'MONGO_USERNAME'),
                        string(credentialsId: 'mongo-password', variable: 'MONGO_PASSWORD')
                    ]) {
                        sh '''
                            echo "MONGO_USERNAME=$MONGO_USERNAME" > .env
                            echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
                            docker-compose up -d --build
                        '''
                    }
                }
            }
        }
        
        stage('Check Container Logs') {
            steps {
                dir("MLOps-lab3") {
                    sh '''
                        container_id=$(docker ps -qf "name=api-container")
                        if [ -z "$container_id" ]; then
                            echo "No container running"
                            exit 1
                        fi
                        docker logs --tail 1000 "$container_id"
                    '''
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                dir('MLOps-lab3') {
                    sh '''
                        image_id=$(docker images -q travissscottt/api-image-3:latest)
                        if [ -z "$image_id" ]; then
                            echo "Error: Docker image not found. Build might have failed."
                            exit 1
                        fi
                        docker push travissscottt/api-image-3:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            sh '''
                docker stop api-container || true
                docker rm api-container || true
                docker stop mongodb-container || true
                docker rm mongodb-container || true
                docker rmi travissscottt/api-image-3:latest || true
                docker rmi mongo || true
                docker logout || true
            '''
            cleanWs()
        }
    }
}
